name: Update recent activity

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
